/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jelena_gajic_onlineshop_JNIsuma */

#ifndef _Included_jelena_gajic_onlineshop_JNIsuma
#define _Included_jelena_gajic_onlineshop_JNIsuma
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jelena_gajic_onlineshop_JNIsuma
 * Method:    suma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jelena_gajic_onlineshop_JNIsuma_suma
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
